# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 28ac5738e3424f4f7565c81be595deab5690afbf67fcbc1555e7895d7bee338bbea7bb6fe69f53cf1bc6e72c55a864766ffe85903e1b233e32f6594309d760e2

test:
  secret_key_base: 64f3d7ea68b556630abdb36efcd92019517a5bf8a4af2ca7d246e6fe9f34f6ac5a4a45447e477bb4edb30621c60fe60e0bb1af0ba1d15f093a13bc076facd7fb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
